/**
* Sometimes a table contains a column that has duplicate values.
* The DISTINCT keyword can be used to return only the unique/distinct values in set column.
*/

-- The DISTINCT keyword operates on a column, example:
-- SELECR DISTINCT column FROM table;

-- Lets look at the film table and use the DISTINCT keyword pair all the duplicate values.

SELECT DISTINCT rental_rate FROM film;

SELECT DISTINCT release_year FROM film;